### ISSUE TITLE
Erro ao importar dados

### ISSUE THREAD

**Issue by arojunior** [arojunior/b3-wallet#19]
Após adicionarem um reCaptcha na tela de login do CEI, o seguinte erro começou a ocorrer:

```sh
=== Coletando dados da B3... Aguarde...
[0] error ao importar dados TimeoutError: waiting for selector "#ctl00_ContentPlaceHolder1_ddlAgentes" failed: timeout 30000ms exceeded
[0]     at new WaitTask (/Users/arojunior/Documents/Projects/b3-wallet/node_modules/puppeteer/lib/DOMWorld.js:549:28)
[0]     at DOMWorld._waitForSelectorOrXPath (/Users/arojunior/Documents/Projects/b3-wallet/node_modules/puppeteer/lib/DOMWorld.js:478:22)
[0]     at DOMWorld.waitForSelector (/Users/arojunior/Documents/Projects/b3-wallet/node_modules/puppeteer/lib/DOMWorld.js:432:17)
[0]     at Frame.waitForSelector (/Users/arojunior/Documents/Projects/b3-wallet/node_modules/puppeteer/lib/FrameManager.js:627:47)
[0]     at Frame.<anonymous> (/Users/arojunior/Documents/Projects/b3-wallet/node_modules/puppeteer/lib/helper.js:112:23)
[0]     at Page.waitForSelector (/Users/arojunior/Documents/Projects/b3-wallet/node_modules/puppeteer/lib/Page.js:1122:29)
[0]     at getExtractData (/Users/arojunior/Documents/Projects/b3-wallet/server/src/scripts/extractData.js:65:16)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
[0]   name: 'TimeoutError'
[0] }

```

**Comment by arojunior** [comment]
Possível solução: https://stackoverflow.com/questions/55678095/bypassing-captchas-with-headless-chrome-using-puppeteer
